branches:
  only:
    - master
dist: trusty  # This is necessary for net-snmp 5.7.2.
language: perl
sudo: required
before_install:
  - sudo apt-get -y install cpanminus libsnmp-perl libsnmp-info-perl
install:
  - sudo cpanm --verbose --installdeps --notest .
script:
  - sudo perl Makefile.PL
  - sudo make manifest
  - sudo make dist
  - sudo RELEASE_TESTING=true cpanm --verbose App-Netsync-*.tar.gz
  - sudo netsync --help
