branches:
  only:
    - master
dist: trusty  # This is necessary for net-snmp 5.7.2.
language: perl
sudo: required
before_install:
  - sudo apt-get -y install cpanminus libsnmp-perl libsnmp-info-perl
install:
  - sudo cpanm --verbose --installdeps --notest .
script:
  - sudo perl -I lib/ bin/netsync.pl --help
  - sudo cpanm --verbose .
